### ISSUE TITLE
Message Champs Obligatoire

### ISSUE THREAD

**Issue by Scombet** [thibaultvanc/fillingo_recettage#47]
-côté front peut-on afficher quand le champs est obligatoire et que l’internaute ne l’a pas rempli uniquement la mention générique : « Ce champs est obligatoire » ? Car quand tu changes l’intitulé dans le formulaire le message qui apparaît en rouge ne correspond plus forcément au nom du champs que tu as changé (exemple : champs raison sociale devenu « agence » par exemple / msg qui apparaît : « Le champs raison sociale est obligatoire »)

**Comment by thibaultvanc** [comment]
ticket en doublon : se referrer à https://github.com/thibaultvanc/fillingo_recettage/issues/48
